### ISSUE TITLE
Application not returned from index.php

### ISSUE THREAD

**Issue by bitkorn** [eth8505/zf-symfony-console#4]
actual ZF3 (zend-mvc: ^3.0.1)

1. Install via composer
2. create a simple command
3. put it to module.config.php
4. run command
5. Application not returned from index.phpPHP Fatal error:  Uncaught Error: Call to a member function getServiceManager() on integer in /var/www/html/gas/camo2/console:17

none apache log

I think the index.php can never return an instance of Application, because index.php return nothing allways.

**Comment by eth8505** [comment]
Per default, nothing is returned from index.php. But to make this work, you have to return the application from index.php

**Comment by bitkorn** [comment]
ah, ok.

```php
// /public/index.php
// ...
$app = Application::init($appConfig);
$app->run();
return $app;
```
...works
