### ISSUE TITLE
HTML output in console

### ISSUE THREAD

**Issue by bitkorn** [eth8505/zf-symfony-console#5]
I have the full HTML from the layout in the console output.

How can we tell ZF3 that it should not make any -view html- output?

**Comment by eth8505** [comment]
Why would you render views for the console at all? That's one of the main points this lib exists, splitting the zend views from the console stuff. 

Anyway, I'll still try to help - can you provide an example of what you're doing so i can try to reproduce?

**Comment by bitkorn** [comment]
I think I have a "normal" MVC ZF3 App.

Composer.json require:

```json
{
"php": "^7.2",
"zendframework/zend-component-installer": "^1.0 || ^0.7 || ^1.0.0-dev@dev",
"zendframework/zend-mvc": "^3.0.1",
"zfcampus/zf-development-mode": "^3.0",
"zendframework/zend-cache": "^2.7.1",
"zendframework/zend-db": "^2.8.1",
"zendframework/zend-mvc-form": "^1.0",
"zendframework/zend-json": "^3.0",
"zendframework/zend-log": "^2.9",
"zendframework/zend-mvc-i18n": "^1.0",
"zendframework/zend-mvc-plugins": "^1.0.1",
"zendframework/zend-psr7bridge": "^0.2.2",
"zendframework/zend-servicemanager-di": "^1.0",
"zendframework/zend-code": "^3.3",
"zendframework/zend-config": "^3.3",
"nette/php-generator": "^3.2",
"zfr/zfr-cors": "^2.0",
"zendframework/zend-mail": "^2.10",
"zendframework/zend-mime": "^2.7",
"ext-fileinfo": "^1.0",
"ralouphie/getallheaders": "^3.0",
"zfcampus/zf-console": "^1.4",
"symfony/console": "^4.3",
"eth8505/zf-symfony-console": "^1.1"
}
```

My command:

```php
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class InstallCommand
 * @package Bitkorn\Trinket\Command
 *
 * Call it with: `php vendor/bin/console app:trinket-install test=blah`
 */
class InstallCommand extends Command
{
    /**
     * @var string The name of the command (the part after "bin/console")
     */
    protected static $defaultName = 'app:trinket-install';

    protected function configure()
    {
        $this->addArgument('test', InputArgument::REQUIRED, 'Only a test.');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $text = 'your argument: ' . $input->getArgument('test');
        $output->writeln($text);
    }
}
```

and module.config.php:

```php
'zfsymfonyconsole_commands' => [
    'invokables' => [
        InstallCommand::class
    ]
]
```

And rund this command:

```bash
php vendor/bin/console app:trinket-install test=blahx
```

That is all what i am doing. I render nothing.

After runt his command, it shows the html and followed by command output:

```bash
...
        <footer>
            <p>&copy; 1970 - 2019 by me</p>
        </footer>
    </div>
    </body>
</html>
your argument: test=blahx
```

**Comment by eth8505** [comment]
I don't think this is a bug - did you ever get it fixed?

**Comment by bitkorn** [comment]
no, not fixed.It works with HTML output.

You are not doing something special so that HTML does not appear?

**Comment by geertijewski** [comment]
The original ZF3 (well Laminas) `public/index.php` ends [with](https://github.com/laminas/laminas-mvc-skeleton/blob/master/public/index.php)

```php
Application::init($appConfig)->run();
```

So `vendor/bin/console` complains that no instance of Application is returned. Changing it to this:
```php
// Run the application!
$app = Application::init($appConfig);
$app->run();
return $app;
```

does run the App, producing the HTML output. And after that the console command is executed, producing that output.

It would be trivial to change `public/index.php` so it does not run the Application when invoked by the console command. The Laminas\Mvc\Application even gives an example:
```php
/**
 * Main application class for invoking applications 
 *
 * ...
 *
 * The most common workflow is:
 * <code>
 * $services = new Laminas\ServiceManager\ServiceManager($servicesConfig);
 * $app      = new Application($appConfig, $services);
 * $app->bootstrap();
 * $response = $app->run();   
 * $response->send();
 * </code>
 *
 * ....
 */
```

So it seems that this library *does work* just that the laminas-mvc-skelton sets the project up in a fashion which makes custom modifications to it necessary, correct?

**Comment by eth8505** [comment]
Thanks for clarifying that @geertijewski , this is actually true. I was sure I added it to the docs, but I didn't. Will do as soon as I find the time.

**Comment by bitkorn** [comment]
ah, ok, `//$app->run();` do the trick :)

`run()`triggers the MvcEvent. Then it is better:

```
if(php_sapi_name() != 'cli') {
    $app->run();
}
```
